# This file configures the deployment settings for Netlify.

[build]
  # The command to build the site.
  command = "npm run build"

  # The directory that contains the built site.
  publish = "dist"

  # Serverless functions directory
  functions = "netlify/functions"

# Serverless functions configuration
[functions]
  node_bundler = "esbuild"

# This rule is important for single-page applications (SPAs).
# It ensures that all paths are redirected to index.html,
# allowing React Router (or any client-side router) to handle them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
